### ISSUE TITLE
Retrieving Linux Server artifacts

### ISSUE THREAD

**Issue by killian-mahe** [NFive/nfpm#32]
The way the lastest linux server artifact is retrieved doesn't work and isn't optimized : 

https://github.com/NFive/nfpm/blob/f033d9accdc8e684f8d1e47850fb851aa1a46c8f/src/Modules/Setup.cs#L205-L244

There is a mistake when the Regex expression is applied. Linux artifacts aren't zipped in `.zip` but in `tar.xz`.
Furthermore, with the new interface, it's clearly easier to retrieved the latest recommended version (Not necessary the latest released) as there is a specific button : 

![image](https://user-images.githubusercontent.com/53428491/81987171-721c9700-9639-11ea-9b65-0dd8f4574017.png)

It's easy to locate this button with his class and get is href url.

**Comment by JoeBiellik** [comment]
The Linux fix is in and I added a ``--fivem-version`` switch so the user can pick the version to use.
