### ISSUE TITLE
Getting stucked in client ready

### ISSUE THREAD

**Issue by Azshurith** [NFive/nfpm#34]
I just installed latest and recommended version, I made the server running however both client and server went stuck to Client ready. Please see attached image.

![image](https://user-images.githubusercontent.com/54873611/85942188-586daf80-b95a-11ea-83f0-45c75f21fd8a.png)

**Comment by TheFuseGamer** [comment]
You don't seem to have any plugins installed. You can start with `nfpm install NFive/plugin-start` and take it from there.

**Comment by Azshurith** [comment]
> You don't seem to have any plugins installed. You can start with `nfpm install NFive/plugin-start` and take it from there.

Wow thank you. That surely made it work!
